routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_user, login_required, logout_user
from app import bcrypt
from src.controllers.dashboardController import dashboardIndex, dashboardSalesData
from src.controllers.productController import index, create, store, edit, update, delete
from src.controllers.transactionController import indexTrans, createTrans, storeTrans, detailTrans
from src.controllers.authController import registerPost, loginPost
from src.controllers.userController import getProfile, editProfile, updateProfile, updatePassword
from src.controllers.datasetController import importIndex, doImportFile
from src.controllers.miningController import eclatIndex, eclatMining, fpGrowthIndex, fpGrowthMining
from src.controllers.miningHistoryController import historyIndex, detailMiningProcess, deleteMiningProcess, generateReport

auth_blueprint = Blueprint('auth_blueprint', __name__, url_prefix='/')
dashboard_blueprint = Blueprint('dashboard_blueprint', __name__)
dataset_blueprint = Blueprint('dataset_blueprint', __name__)
product_blueprint = Blueprint('product_blueprint', __name__)
transaction_blueprint = Blueprint('transaction_blueprint', __name__)
mining_blueprint = Blueprint('mining_blueprint', __name__)
mining_history_blueprint = Blueprint('mining_history_blueprint', __name__)
user_blueprint = Blueprint('user_blueprint', __name__)


# ---------------------------------------------------------------------
# Authentication
@auth_blueprint.route("/", methods=["GET", "POST"])
def login():
    if request.method == 'GET': return render_template('auth/login.html')
    if request.method == 'POST': return loginPost(bcrypt)
    else: return "Method not allowed"


@auth_blueprint.route("/register", methods=["GET", "POST"])
def register():
    if request.method == 'GET': return render_template('auth/register.html')
    if request.method == 'POST': return registerPost(bcrypt)
    else: return "Method not allowed"

@auth_blueprint.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth_blueprint.login'))


# ---------------------------------------------------------------------
# Home
@dashboard_blueprint.route("/dashboard", methods=["GET"])
@login_required
def dashboard():
    return dashboardIndex()

@dashboard_blueprint.route("/transactions/sales-data", methods=["GET"])
@login_required
def sales_data():
    return dashboardSalesData()


# ---------------------------------------------------------------------
# Import Dataset
@dataset_blueprint.route("/import", methods=["GET", "POST"])
@login_required
def do_import():
    if request.method == 'GET': return importIndex()
    if request.method == 'POST': return doImportFile()
    else: return "Method not allowed"


# ---------------------------------------------------------------------
# Product
# @product_blueprint.route("/products", methods=["GET"])
# @login_required
# def list_product():
#     if request.method == 'GET': return index()
#     else: return "Method not allowed"

@product_blueprint.route("/products/")
@login_required
def list_product():
    return render_template('product/list_product.html')

@product_blueprint.route("/products/data", methods=["GET"])
@login_required
def list_product_data():
    return index()

@product_blueprint.route("/products/create", methods=["GET", "POST"])
@login_required
def create_product():
    if request.method == 'GET': return create()
    if request.method == 'POST': return store()
    else: return "Method not allowed"

@product_blueprint.route("/products/<itemCode>/edit", methods=["GET", "POST"])
@login_required
def edit_product(itemCode):
    if request.method == 'GET': return edit(itemCode)
    if request.method == 'POST': return update(itemCode)
    else: return "Method not allowed"

@product_blueprint.route("/products/<itemCode>/delete", methods=["POST"])
@login_required
def delete_product(itemCode):
    return delete(itemCode)


# ---------------------------------------------------------------------
# Transaction
@transaction_blueprint.route("/transaction/")
@login_required
def list_transaction():
    return render_template('transaction/list_transaction.html')

@transaction_blueprint.route("/transaction/data", methods=["GET"])
@login_required
def list_transaction_data():
    return indexTrans()

@transaction_blueprint.route("/transaction/create", methods=["GET", "POST"])
@login_required
def create_transaction():
    if request.method == 'GET': return createTrans()
    if request.method == 'POST': return storeTrans()
    else: return "Method not allowed"
    
@transaction_blueprint.route("/transaction/<transaction_id>/detail", methods=["GET"])
@login_required
def detail_transaction(transaction_id):
    return detailTrans(transaction_id)


# ---------------------------------------------------------------------
# Association Mining
@mining_blueprint.route("/eclat", methods=["GET", "POST"])
@login_required
def eclat_mining():
    if request.method == 'GET': return eclatIndex()
    if request.method == 'POST': return eclatMining()
    else: return "Method not allowed"
    
@mining_blueprint.route("/fp-growth", methods=["GET", "POST"])
@login_required
def fpgrowth_mining():
    if request.method == 'GET': return fpGrowthIndex()
    if request.method == 'POST': return fpGrowthMining()
    else: return "Method not allowed"


# ---------------------------------------------------------------------
# Mining History
@mining_history_blueprint.route("/mining-history", methods=["GET"])
@login_required
def mining_history():
    if request.method == 'GET': return historyIndex()
    else: return "Method not allowed"
    
@mining_history_blueprint.route("/mining-history/<process_id>/detail", methods=["GET"])
@login_required
def detail_mining_history(process_id):
    return detailMiningProcess(process_id)


@mining_history_blueprint.route("/mining-history/<process_id>/delete", methods=["POST"])
@login_required
def delete_mining_history(process_id):
    return deleteMiningProcess(process_id)

@mining_history_blueprint.route("/mining-history/<process_id>/report", methods=["GET"])
@login_required
def mining_history_report(process_id):
    return generateReport(process_id)


# ---------------------------------------------------------------------
# User
@user_blueprint.route("/profile", methods=["GET", "POST"])
@login_required
def profile():
    if request.method == 'GET': return getProfile()
    if request.method == 'POST': return updatePassword(bcrypt)
    else: return "Method not allowed"

@user_blueprint.route("/profile/<user_id>/edit", methods=["GET", "POST"])
@login_required
def edit_profile(user_id):
    if request.method == 'GET': return editProfile(user_id)
    if request.method == 'POST': return updateProfile(user_id)
    else: return "Method not allowed"

src/controllers/miningHistoryController.py
from flask import render_template, request, redirect, url_for, flash, Response
import time
from app import db
from src.models.transaction import Transaction
from src.models.mining import MiningProcess, AssociationResult, AssociationResultProduct
from src.models.product import Product
from fpdf import FPDF


def historyIndex():
    mining_process = MiningProcess.query.all()
    
    return render_template("mining_history/history_index.html", mining_process=mining_process)


def deleteMiningProcess(process_id):
    mining_process = MiningProcess.query.get(process_id)

    if mining_process:
        db.session.delete(mining_process)
        db.session.commit()
        print(f"Data mining process dengan ID {process_id} telah dihapus.")
    else:
        print(f"Data mining process dengan ID {process_id} tidak ditemukan.")
    
    return redirect(url_for('mining_history_blueprint.mining_history'))


def getMiningProcess(process_id):
    mining_process = MiningProcess.query.get(process_id)

    query = db.session.query(
        AssociationResultProduct.association_result_id,
        AssociationResultProduct.is_antecedent,
        AssociationResult.support,
        AssociationResult.confidence,
        AssociationResult.lift,
        Product.itemCode,
        Product.name.label("item_name")
    ).join(AssociationResult).join(
        Product, AssociationResultProduct.itemCode == Product.itemCode
    ).filter(AssociationResult.mining_process_id == process_id)

    results = query.all()

    associations = {}
    for result in results:
        association_id = result.association_result_id
        if association_id not in associations:
            associations[association_id] = {
                'antecedent': set(),
                'consequent': set(),
                'support': result.support,
                'confidence': result.confidence,
                'lift': result.lift,
            }
        if result.is_antecedent:
            associations[association_id]['antecedent'].add((result.itemCode, result.item_name))
        else:
            associations[association_id]['consequent'].add((result.itemCode, result.item_name))

    sorted_associations = sorted(associations.items(), key=lambda x: x[1]['confidence'], reverse=True)
    
    return mining_process, sorted_associations


def detailMiningProcess(process_id):
    mining_process, associations = getMiningProcess(process_id)
    
    sorted_associations = sorted(associations, key=lambda x: x[1]['confidence'], reverse=True)
    
    lenOfAssociation = len(sorted_associations)
        
    return render_template('mining_history/detail_mining_history.html',
                           mining_process=mining_process,
                           associations=sorted_associations,
                           lenOfAssociation=lenOfAssociation)


def generateReport(process_id):
    pdf = FPDF()
    pdf.add_font('Calibri', '', r"c:\WINDOWS\Fonts\Calibri.ttf", uni=True)
    margin_x = 15
    margin_y = 20
    pdf.set_margins(margin_x, margin_y)
    pdf.add_page()
    
    page_width = pdf.w - 2 * pdf.l_margin
    
    pdf.set_font('Arial', 'B', 14.0)
    pdf.cell(page_width, 0.0, 'Sinar Mart', align='L')
    pdf.ln(5)
    pdf.set_font('Arial', '', 11.0)
    pdf.cell(page_width, 0.0, 'Jl. D.I Panjaitan No 88 A, Lepo - Lepo', align='L')
    pdf.ln(10)
    pdf.set_font('Arial', 'B', 12.0)
    pdf.cell(page_width, 0.0, 'LAPORAN HASIL ANALISIS ASOSIASI', align='L')
    pdf.ln(5)
    
    no_col_width = 10
    col_width_temp = (page_width - no_col_width)/4
    association_col_width = (col_width_temp * 2) + (no_col_width * 2) - no_col_width
    col_width = (page_width - association_col_width - no_col_width)/2
        
    th = pdf.font_size
    
    pdf.set_font('Arial', 'B', 10)
    pdf.set_fill_color(235, 235, 235)
    pdf.cell(no_col_width, th + 5, 'No.', border=1, align='C', fill=True)
    pdf.cell(association_col_width, th + 5, 'Aturan Asosiasi', border=1, align='C', fill=True)
    pdf.cell(col_width, th + 5, 'Support (%)', border=1, align='C', fill=True)
    pdf.cell(col_width, th + 5, 'Confidence (%)', border=1, align='C', fill=True)
    # pdf.cell(col_width, th + 5, 'Nilai Lift', border=1, align='C', fill=True)
    pdf.ln(th + 5)
    
    pdf.set_font('Calibri', '', 10)
    
    mining_process, associations = getMiningProcess(process_id)
   
    row_number = 1
    for association_id, association in associations:
        pdf.set_fill_color(255, 255, 255)

        antecedent_text = "\n".join([f"{item[0]} - {item[1]}" for item in association['antecedent']])
        consequent_text = "\n".join([f"{item[0]} - {item[1]}" for item in association['consequent']])
        combined_text = f"Jika membeli:\n{antecedent_text}\nMaka berpotensi membeli:\n{consequent_text}"

        # Calculate the height of the multi-cell content
        lines = combined_text.split('\n')
        multi_cell_height = (th + 2) * len(lines)
    
        # Nomor dan aturan asosiasi
        pdf.cell(no_col_width, multi_cell_height, str(row_number), border=1, align='C')
        
        currrent_x = pdf.get_x()
        currrent_y = pdf.get_y()

        pdf.multi_cell(association_col_width, th + 2, combined_text, border=1)
        
        # Support, confidence, dan lift
        pdf.set_xy(currrent_x + association_col_width, currrent_y)
        pdf.cell(col_width, multi_cell_height, "{:.2f}".format(association['support']*100), border=1, align='C')
        pdf.cell(col_width, multi_cell_height, "{:.2f}".format(association['confidence']*100), border=1, align='C')
        # pdf.cell(col_width, multi_cell_height, "{:.2f}".format(association['lift']), border=1, align='C')

        # Pindah ke baris berikutnya
        pdf.ln()
        
        currrent_x = pdf.get_x()
        currrent_y = pdf.get_y()
        pdf.set_xy(currrent_x, currrent_y)
        

        row_number += 1


    pdf.ln(10)
    
    
    pdf.set_font('Times', '', 10.0)
    pdf.cell(page_width, 0.0, '- end of report -', align='C')
    
    return Response(pdf.output(dest='S').encode('latin-1'), mimetype='application/pdf', headers={'Content-Disposition':'attachment; filename=mining-report.pdf'})


# def detailMiningProcess(process_id):
#     mining_process = MiningProcess.query.get(process_id)
    
#     query = db.session.query(
#         AssociationResultProduct.association_result_id,
#         AssociationResultProduct.itemCode,
#         AssociationResultProduct.is_antecedent,
#         AssociationResult.support,
#         AssociationResult.confidence,
#         AssociationResult.lift,
#         # Product.itemCode.label("product_item_code")
#     )

#     # Bergabung dengan tabel AssociationResult untuk mendapatkan support, confidence, dan lift
#     query = query.join(AssociationResult, AssociationResultProduct.association_result_id == AssociationResult.id)

#     # Bergabung dengan tabel Product untuk mendapatkan itemCode dari produk terkait
#     query = query.join(Product, AssociationResultProduct.itemCode == Product.itemCode)

#     # Menambahkan filter berdasarkan mining_process_id
#     query = query.filter(AssociationResult.mining_process_id == process_id)

#     # Eksekusi query dan ambil hasilnya
#     results = query.all()
    
#     associations = {}
#     for result in results:
#         association_id = result.association_result_id
#         if association_id not in associations:
#             associations[association_id] = {
#                 'antecedent': set(),
#                 'consequent': set(),
#                 'support': result.support,
#                 'confidence': result.confidence,
#                 'lift': result.lift,
#             }
#         if result.is_antecedent:
#             associations[association_id]['antecedent'].add(result.itemCode)
#         else:
#             associations[association_id]['consequent'].add(result.itemCode)
    
#     return render_template('mining_history/detail_mining_history.html', mining_process=mining_process, associations=associations)

templates/mining_history/detail_mining_history.html
{% extends 'base_admin.html' %} {% block title %} Detail Riwayat Analisis {%
endblock %} {% block content %}

<h3 class="mb-5">Detail Analisis</h3>

<div class="card">
  <div class="card-body">
    <h5 class="card-title fw-semibold mb-4">Informasi Hasil Analisis</h5>

    <table class="table table-borderless">
      <tbody>
        <tr>
          <th scope="row" width="25%" style="padding: 5px 0px !important">
            Algoritma
          </th>
          <td style="padding: 5px 0px !important">
            {{ mining_process.algorithm }}
          </td>
        </tr>
        <tr>
          <th scope="row" style="padding: 5px 0px !important">
            Periode Transaksi
          </th>
          <td style="padding: 5px 0px !important">
            <span id="periodStart">{{ mining_process.period_start }}</span> s.d.
            <span id="periodEnd"> {{mining_process.period_end}} </span>
          </td>
        </tr>
        <tr>
          <th scope="row" style="padding: 5px 0px !important">
            {% if mining_process.algorithm == 'ECLAT' %} Minimum Support {% else
            %} Minimum Support Count {% endif %}
          </th>
          <td style="padding: 5px 0px !important">
            {% if mining_process.algorithm == 'ECLAT' %}
            <span>{{ mining_process.minimum_support }}%</span>
            {% else %}
            <span>{{ mining_process.minimum_support|int }}</span>
            {% endif %}
          </td>
        </tr>
        <tr>
          <th scope="row" style="padding: 5px 0px !important">
            Minimum Confidence
          </th>
          <td style="padding: 5px 0px !important">
            {{ mining_process.minimum_confidence }}%
          </td>
        </tr>
        <tr>
          <th scope="row" style="padding: 5px 0px !important">
            Waktu Analisis
          </th>
          <td class="analysisDate" style="padding: 5px 0px !important">
            {{ mining_process.created_at }}
          </td>
        </tr>
        <tr>
          <th scope="row" style="padding: 5px 0px !important">
            Total Asosiasi
          </th>
          <td style="padding: 5px 0px !important">{{ lenOfAssociation }}</td>
        </tr>
        <tr>
          <th scope="row" style="padding: 5px 0px !important">
            Waktu Eksekusi
          </th>
          <td
            id="executionTimeCell"
            data-value="{{ mining_process.execution_time }}"
            style="padding: 5px 0px !important"
          ></td>

          <!-- <td id="executionTimeCell" style="padding: 5px 0px !important">
            {{ mining_process.execution_time }} Detik
          </td> -->
        </tr>
        <tr>
          <th scope="row" style="padding: 5px 0px !important">
            Konsumsi Memori
          </th>
          <td style="padding: 5px 0px !important">
            {{ mining_process.memory_consumtion }} MB
          </td>
        </tr>
      </tbody>
    </table>

    <a
      href="{{ url_for('mining_history_blueprint.mining_history') }}"
      class="btn btn-light mt-3"
    >
      Kembali
    </a>
  </div>
</div>

<div class="card" id="rules-card">
  <div class="card-body">
    <div class="d-flex justify-content-between">
      <h5 class="card-title fw-semibold mb-4">Hasil Analisis</h5>
      <div>
        <a
          href="{{ url_for('mining_history_blueprint.mining_history_report', process_id=mining_process.id) }}"
          class="btn btn-sm btn-outline-danger"
          title="Cetak Asosiasi"
          aria-label="Cetak Asosiasi"
          ><span>
            <i class="ti ti-file-text"></i> Cetak Hasil Analisis (PDF)</span
          ></a
        >
      </div>
    </div>

    <table id="associated_rules_history" class="table display">
      <thead>
        <tr>
          <th scope="col">No</th>
          <th scope="col">Aturan Asosiasi</th>
          <th scope="col">Nilai Support (%)</th>
          <th scope="col">Nilai Confidence (%)</th>
          <th scope="col">Lift Ratio</th>
        </tr>
      </thead>
      <tbody>
        {% for association_id, association in associations %}
        <tr>
          <td>{{loop.index}}</td>
          <td>
            Jika membeli
            <br />
            {% for item in association.antecedent %}
            <b>{{ item[0] }} - {{ item[1] }}</b>
            <br />
            {% endfor %} Maka berpotensi membeli
            <br />
            {% for item in association.consequent %}
            <b>{{ item[0] }} - {{ item[1] }}</b>
            <br />
            {% endfor %}
          </td>
          <td>{{ association.support|float|round(3) }}</td>
          <td>{{ association.confidence|float|round(3) }}</td>
          <td>{{ association.lift|float|round(3) }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %} {% block scripts %}
<script>
  $(document).ready(function () {
    $("#associated_rules_history").DataTable({
      language: {
        url: "https://cdn.datatables.net/plug-ins/1.10.25/i18n/Indonesian.json",
      },
      iDisplayLength: 5,
    });
  });

  $(document).ready(function () {
    $("#periodStart, #periodEnd").each(function () {
      var dateElement = $(this);
      var date = new Date(dateElement.text());

      var day = date.getDate();
      var month = date.getMonth() + 1; // Perhatikan bahwa bulan dimulai dari 0, sehingga perlu ditambahkan 1
      var year = date.getFullYear();

      var formattedDate = day + "/" + month + "/" + year;

      dateElement.text(formattedDate);
    });
  });

  $(document).ready(function () {
    $(".analysisDate").each(function () {
      var dateElement = $(this);
      var date = new Date(dateElement.text());

      var day = date.getDate();
      var month = date.getMonth() + 1; // Perlu ditambah 1 karena bulan dimulai dari 0
      var year = date.getFullYear();
      var time = date.toLocaleTimeString([], {
        hour: "2-digit",
        minute: "2-digit",
      });

      var formattedDate = day + "/" + month + "/" + year + ", " + time;
      dateElement.text(formattedDate);
    });
  });

  var executionTime = $("#executionTimeCell").attr("data-value");
  console.log(executionTime);
  var executionTimeCell = document.getElementById("executionTimeCell");

  // Konversi waktu sesuai dengan satuan yang tepat
  var formattedTime = convertTime(executionTime);

  // Tampilkan hasil di dalam elemen HTML
  executionTimeCell.textContent = formattedTime;

  function convertTime(timeInSeconds) {
    var seconds = Math.floor(timeInSeconds) % 60;
    var minutes = Math.floor(timeInSeconds / 60) % 60;
    var hours = Math.floor(timeInSeconds / 3600);

    var formattedTime = "";

    if (hours > 0) {
      formattedTime += hours + " Jam ";
    }

    if (minutes > 0 || hours > 0) {
      formattedTime += minutes + " Menit ";
    }

    if (seconds > 0 || (hours === 0 && minutes === 0)) {
      formattedTime += seconds + " Detik";
    }

    return formattedTime.trim();
  }
</script>
{% endblock %}

templates/mining_history/history_index.html
{% extends 'base_admin.html' %} {% block title %} Riwayat Penambangan {%
endblock %} {% set current_page = 'history' %} {% block content %}
<h3 class="mb-5">Riwayat Analisis</h3>

<div class="card">
  <div class="card-body">
    <table id="miningHistoryData" class="table display">
      <thead>
        <tr>
          <th scope="col">No</th>
          <th scope="col">Algoritma</th>
          <th scope="col">Periode Transaksi</th>
          <th scope="col">Minimum Support</th>
          <th scope="col">Minimum Confidence (%)</th>
          <th scope="col">Waktu Analisis</th>
          <!-- <th scope="col">Waktu Eksekusi</th> -->
          <th scope="col">Aksi</th>
        </tr>
      </thead>
      <tbody>
        {% for process in mining_process %}
        <tr>
          <td>{{loop.index}}</td>
          <td>{{process.algorithm}}</td>
          <td>
            <span id="periodStart">{{process.period_start}}</span>
            s.d
            <span id="periodEnd">{{process.period_end}}</span>
          </td>
          <!-- <td>{{process.minimum_support}}</td> -->
          <td>
            {% if process.algorithm == 'ECLAT' %}
            <span>{{ process.minimum_support }}%</span>
            {% else %}
            <span>{{ process.minimum_support|int }}</span>
            {% endif %}
          </td>
          <td>{{process.minimum_confidence}}</td>
          <td class="analysisDate">{{process.created_at}}</td>
          <td>
            <div class="d-flex justify-content-left">
              <a
                href="{{ url_for('mining_history_blueprint.detail_mining_history', process_id=process.id) }}"
                class="btn btn-sm btn-outline-primary"
                title="Lihat Detail"
                aria-label="Lihat Detail"
              >
                <div class="d-flex align-items-center">
                  <span><i class="ti ti-eye"></i></span>
                  <span class="ml-2">&nbsp;Detail</span>
                </div>
              </a>

              <form
                method="post"
                action="{{ url_for('mining_history_blueprint.delete_mining_history', process_id=process.id) }}"
                onsubmit="return deleteMiningHistoryConfirmation('{{ process.id }}')"
              >
                <button
                  type="submit"
                  class="btn btn-sm btn-outline-danger"
                  style="margin-left: 5px"
                  title="Hapus"
                  aria-label="Hapus"
                >
                  <div class="d-flex align-items-center">
                    <span><i class="ti ti-eye"></i></span>
                    <span class="ml-2">&nbsp;Hapus</span>
                  </div>
                </button>
              </form>

              <script>
                function deleteMiningHistoryConfirmation(item) {
                  if (
                    confirm(
                      "Anda yakin ingin menghapus riwayat mining id: " +
                        item +
                        " dari database?"
                    )
                  ) {
                    return true;
                  } else {
                    return false;
                  }
                }
              </script>
            </div>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %} {% block scripts %}
<script>
  $(document).ready(function () {
    $("#miningHistoryData").DataTable({
      language: {
        url: "https://cdn.datatables.net/plug-ins/1.10.25/i18n/Indonesian.json",
      },
    });
  });

  $(document).ready(function () {
    $("#periodStart, #periodEnd").each(function () {
      var dateElement = $(this);
      var date = new Date(dateElement.text());

      var day = date.getDate();
      var month = date.getMonth() + 1; // Perhatikan bahwa bulan dimulai dari 0, sehingga perlu ditambahkan 1
      var year = date.getFullYear();

      var formattedDate = day + "/" + month + "/" + year;

      dateElement.text(formattedDate);
    });
  });

  $(document).ready(function () {
    $(".analysisDate").each(function () {
      var dateElement = $(this);
      var date = new Date(dateElement.text());

      var day = date.getDate();
      var month = date.getMonth() + 1; // Perlu ditambah 1 karena bulan dimulai dari 0
      var year = date.getFullYear();
      var time = date.toLocaleTimeString([], {
        hour: "2-digit",
        minute: "2-digit",
      });

      var formattedDate = day + "/" + month + "/" + year + ", " + time;
      dateElement.text(formattedDate);
    });
  });
</script>
{% endblock %}