src/models/product.py
from app import db

class Product(db.Model):
    __tablename__ = 'products'

    itemCode = db.Column(db.String, primary_key=True)
    name = db.Column(db.String(), nullable=False)    
    unit = db.Column(db.String(), nullable=False)    
    price = db.Column(db.Integer(), nullable=False)   
    transactions = db.relationship('TransactionProduct', backref='product', lazy='dynamic') 


    def __init__(self, itemCode, name, unit, price):
        self.itemCode = itemCode        
        self.name = name      
        self.unit = unit      
        self.price = price


    def __repr__(self):
        return f"<User {self.itemCode}>"

routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_user, login_required, logout_user
from app import bcrypt
from src.controllers.dashboardController import dashboardIndex, dashboardSalesData
from src.controllers.productController import index, create, store, edit, update, delete
from src.controllers.transactionController import indexTrans, createTrans, storeTrans, detailTrans
from src.controllers.authController import registerPost, loginPost
from src.controllers.userController import getProfile, editProfile, updateProfile, updatePassword
from src.controllers.datasetController import importIndex, doImportFile
from src.controllers.miningController import eclatIndex, eclatMining, fpGrowthIndex, fpGrowthMining
from src.controllers.miningHistoryController import historyIndex, detailMiningProcess, deleteMiningProcess, generateReport

auth_blueprint = Blueprint('auth_blueprint', __name__, url_prefix='/')
dashboard_blueprint = Blueprint('dashboard_blueprint', __name__)
dataset_blueprint = Blueprint('dataset_blueprint', __name__)
product_blueprint = Blueprint('product_blueprint', __name__)
transaction_blueprint = Blueprint('transaction_blueprint', __name__)
mining_blueprint = Blueprint('mining_blueprint', __name__)
mining_history_blueprint = Blueprint('mining_history_blueprint', __name__)
user_blueprint = Blueprint('user_blueprint', __name__)


# ---------------------------------------------------------------------
# Authentication
@auth_blueprint.route("/", methods=["GET", "POST"])
def login():
    if request.method == 'GET': return render_template('auth/login.html')
    if request.method == 'POST': return loginPost(bcrypt)
    else: return "Method not allowed"


@auth_blueprint.route("/register", methods=["GET", "POST"])
def register():
    if request.method == 'GET': return render_template('auth/register.html')
    if request.method == 'POST': return registerPost(bcrypt)
    else: return "Method not allowed"

@auth_blueprint.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth_blueprint.login'))


# ---------------------------------------------------------------------
# Home
@dashboard_blueprint.route("/dashboard", methods=["GET"])
@login_required
def dashboard():
    return dashboardIndex()

@dashboard_blueprint.route("/transactions/sales-data", methods=["GET"])
@login_required
def sales_data():
    return dashboardSalesData()


# ---------------------------------------------------------------------
# Import Dataset
@dataset_blueprint.route("/import", methods=["GET", "POST"])
@login_required
def do_import():
    if request.method == 'GET': return importIndex()
    if request.method == 'POST': return doImportFile()
    else: return "Method not allowed"


# ---------------------------------------------------------------------
# Product
# @product_blueprint.route("/products", methods=["GET"])
# @login_required
# def list_product():
#     if request.method == 'GET': return index()
#     else: return "Method not allowed"

@product_blueprint.route("/products/")
@login_required
def list_product():
    return render_template('product/list_product.html')

@product_blueprint.route("/products/data", methods=["GET"])
@login_required
def list_product_data():
    return index()

@product_blueprint.route("/products/create", methods=["GET", "POST"])
@login_required
def create_product():
    if request.method == 'GET': return create()
    if request.method == 'POST': return store()
    else: return "Method not allowed"

@product_blueprint.route("/products/<itemCode>/edit", methods=["GET", "POST"])
@login_required
def edit_product(itemCode):
    if request.method == 'GET': return edit(itemCode)
    if request.method == 'POST': return update(itemCode)
    else: return "Method not allowed"

@product_blueprint.route("/products/<itemCode>/delete", methods=["POST"])
@login_required
def delete_product(itemCode):
    return delete(itemCode)


# ---------------------------------------------------------------------
# Transaction
@transaction_blueprint.route("/transaction/")
@login_required
def list_transaction():
    return render_template('transaction/list_transaction.html')

@transaction_blueprint.route("/transaction/data", methods=["GET"])
@login_required
def list_transaction_data():
    return indexTrans()

@transaction_blueprint.route("/transaction/create", methods=["GET", "POST"])
@login_required
def create_transaction():
    if request.method == 'GET': return createTrans()
    if request.method == 'POST': return storeTrans()
    else: return "Method not allowed"
    
@transaction_blueprint.route("/transaction/<transaction_id>/detail", methods=["GET"])
@login_required
def detail_transaction(transaction_id):
    return detailTrans(transaction_id)


# ---------------------------------------------------------------------
# Association Mining
@mining_blueprint.route("/eclat", methods=["GET", "POST"])
@login_required
def eclat_mining():
    if request.method == 'GET': return eclatIndex()
    if request.method == 'POST': return eclatMining()
    else: return "Method not allowed"
    
@mining_blueprint.route("/fp-growth", methods=["GET", "POST"])
@login_required
def fpgrowth_mining():
    if request.method == 'GET': return fpGrowthIndex()
    if request.method == 'POST': return fpGrowthMining()
    else: return "Method not allowed"


# ---------------------------------------------------------------------
# Mining History
@mining_history_blueprint.route("/mining-history", methods=["GET"])
@login_required
def mining_history():
    if request.method == 'GET': return historyIndex()
    else: return "Method not allowed"
    
@mining_history_blueprint.route("/mining-history/<process_id>/detail", methods=["GET"])
@login_required
def detail_mining_history(process_id):
    return detailMiningProcess(process_id)


@mining_history_blueprint.route("/mining-history/<process_id>/delete", methods=["POST"])
@login_required
def delete_mining_history(process_id):
    return deleteMiningProcess(process_id)

@mining_history_blueprint.route("/mining-history/<process_id>/report", methods=["GET"])
@login_required
def mining_history_report(process_id):
    return generateReport(process_id)


# ---------------------------------------------------------------------
# User
@user_blueprint.route("/profile", methods=["GET", "POST"])
@login_required
def profile():
    if request.method == 'GET': return getProfile()
    if request.method == 'POST': return updatePassword(bcrypt)
    else: return "Method not allowed"

@user_blueprint.route("/profile/<user_id>/edit", methods=["GET", "POST"])
@login_required
def edit_profile(user_id):
    if request.method == 'GET': return editProfile(user_id)
    if request.method == 'POST': return updateProfile(user_id)
    else: return "Method not allowed"

src/controllers/productController.py
from flask import render_template, request, redirect, url_for, flash, jsonify
from app import db
from src.models.product import Product
from sqlalchemy import text, or_


def index():
    try:
        # Mengambil parameter paging dan sorting dari permintaan Ajax
        draw = int(request.args.get('draw', 1))
        start = int(request.args.get('start', 0))
        length = int(request.args.get('length', 10))
        order_column_index = int(request.args.get('order[0][column]', 1))
        order_dir = request.args.get('order[0][dir]', 'asc')
        search_value = request.args.get('search[value]', '')

        # Menentukan kolom apa yang dapat diurutkan
        sortable_columns = ['itemCode', 'name']
        order_column_name = sortable_columns[min(order_column_index, len(sortable_columns) - 1)]

        # Menentukan arah pengurutan
        if order_dir == 'asc':
            order_clause = f"{order_column_name} ASC"
        else:
            order_clause = f"{order_column_name} DESC"

        # Mengambil data untuk halaman tertentu dengan paging dan sorting
        query = Product.query.filter(
            or_(
                Product.itemCode.ilike(f"%{search_value}%"),
                Product.name.ilike(f"%{search_value}%"),
            )
        )
        
        total_records = query.count()
        productsData = query.order_by(text(order_clause)).offset(start).limit(length).all()

        products = []
        for transaction in productsData:
            products.append({
                'Kode Barang': transaction.itemCode,
                'Nama Barang': transaction.name,
            })

        return jsonify({
            'draw': draw,
            'recordsTotal': total_records,
            'recordsFiltered': total_records,
            'data': products,
        })
    except Exception as e:
        print(f"Error in index: {str(e)}")
        return jsonify({'error': 'Internal Server Error'}), 500


def create():
    return render_template('product/create_product.html')


def store():
    request_form = request.form.to_dict()
    
    new_item = Product(
        itemCode = request_form['itemCode'],
        name = request_form['name'],
        # price = request_form['price'],
        price = 0,
        unit=""
        )
    
    db.session.add(new_item)
    db.session.commit()
    
    flash('Barang baru berhasil disimpan.')
    
    return redirect(url_for('product_blueprint.list_product'))


def edit(itemCode):
    product = Product.query.get(itemCode)
    
    return render_template('product/edit_product.html', product=product)


def update(itemCode):
    request_form = request.form.to_dict()
    product = Product.query.get(itemCode)
    
    product.name = request_form['name']
    # product.price = request_form['price']
    product.price = 0

    db.session.commit()
    
    flash('Barang dengan kode \'{}\' berhasil diperbarui.'.format(product.itemCode))
    
    return redirect(url_for('product_blueprint.list_product'))


def delete(itemCode):
    print("itemCode", itemCode)
    product = Product.query.filter_by(itemCode=itemCode).first()
    
    if product:
        # Hapus produk berdasarkan 'itemCode'
        db.session.delete(product)
        db.session.commit()
    
    flash('Barang dengan kode {} berhasil dihapus.'.format(itemCode))
    
    return redirect(url_for('product_blueprint.list_product'))

templates/product/create_product.html
{% extends 'base_admin.html' %} {% block title %} Tambah Produk {% endblock %}
{% block content %}

<h3 class="mb-5">Tambah Barang</h3>

<div class="card">
  <div class="card-body">
    <form
      action="{{ url_for('product_blueprint.create_product') }}"
      method="POST"
    >
      <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Kode Barang</label>
        <input
          type="text"
          class="form-control"
          id="itemCode"
          name="itemCode"
          required
        />
      </div>
      <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Nama Barang</label>
        <input
          type="text"
          class="form-control"
          id="name"
          name="name"
          required
        />
      </div>
      <!-- <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Harga Jual</label>
        <input
          type="number"
          class="form-control"
          id="price"
          name="price"
          required
        />
      </div> -->

      <button type="submit" class="btn btn-primary">Simpan</button>
      <a
        href="{{ url_for('product_blueprint.list_product') }}"
        class="btn btn-light mx-3"
        >Batal</a
      >
    </form>
  </div>
</div>

{% endblock %}

templates/product/edit_product.html
{% extends 'base_admin.html' %} {% block title %} Edit Produk {% endblock %} {%
block content %}

<h3 class="mb-5">Edit Barang</h3>

<div class="card">
  <div class="card-body">
    <form
      action="{{ url_for('product_blueprint.edit_product', itemCode=product.itemCode) }}"
      method="POST"
    >
      <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Kode Barang</label>
        <input
          type="text"
          class="form-control"
          id="itemCode"
          name="itemCode"
          value="{{ product.itemCode }}"
          readonly
          title="Kode produk tidak dapat diubah!"
        />
        <div id="itemCode" class="form-text">
          Kode produk tidak dapat diubah!
        </div>
      </div>
      <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Nama Barang</label>
        <input
          type="text"
          class="form-control"
          id="name"
          name="name"
          value="{{ product.name }}"
          required
        />
      </div>
      <!-- <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Harga</label>
        <input
          type="number"
          class="form-control"
          id="price"
          name="price"
          value="{{ product.price }}"
          required
        />
      </div> -->

      <button type="submit" class="btn btn-primary">Perbarui</button>

      <a
        href="{{ url_for('product_blueprint.list_product') }}"
        class="btn btn-light mx-3"
        >Batal</a
      >
    </form>
  </div>
</div>

{% endblock %}

templates/product/list_product.html
{% extends 'base_admin.html' %} {% block title %} Master Produk {% endblock %}
{% set current_page = 'product' %} {% block content %}

<div class="d-flex justify-content-between mb-5">
  <h3>Data Barang</h3>
  <div>
    <a
      href="{{ url_for('product_blueprint.create_product') }}"
      class="btn btn-primary"
      >Tambah Barang</a
    >
  </div>
</div>

<div class="card">
  <div class="card-body">
    {% with messages = get_flashed_messages() %} {% if messages %}
    <div class="alert alert-success" role="alert">{{ messages[0] }}</div>
    {% endif %} {% endwith %}

    <table id="data" class="table display">
      <thead>
        <tr>
          <th scope="col">No.</th>
          <th scope="col">Kode Barang</th>
          <th scope="col">Nama Barang</th>
          <!-- <th scope="col">Satuan</th> -->
          <!-- <th scope="col">Harga Jual</th> -->
          <th scope="col">Tindakan</th>
        </tr>
      </thead>
      <tbody>
        {% for item in products %}
        <tr>
          <td>{{ loop.index }}</td>
          <td>{{ item['Kode Barang'] }}</td>
          <td>{{ item['Nama Barang'] }}</td>
          <!-- <td>{{ item.unit }}</td> -->
          <!-- <td id="price">{{ item.price }}</td> -->
          <td>
            <div class="d-flex justify-content-left">
              <a
                href="{{ url_for('product_blueprint.edit_product', itemCode=item['Kode Barang']) }}"
                class="btn btn-sm btn-outline-primary"
                title="Edit"
                aria-label="Edit"
                ><span> <i class="ti ti-edit"></i> Edit </span></a
              >
              <!-- <form
                method="post"
                action="{{ url_for('product_blueprint.delete_product', itemCode=item.itemCode) }}"
                onsubmit="return deleteProductConfirmation('{{ item.name }}')"
              >
                <button
                  type="submit"
                  class="btn btn-sm btn-outline-danger"
                  style="margin-left: 5px"
                  title="Hapus"
                  aria-label="Hapus"
                >
                  <span><i class="ti ti-trash"></i> Hapus</span>
                </button>
              </form> -->
            </div>
          </td>
          <!-- <td>
            <a
              href="{{ url_for('product_blueprint.edit_product', itemCode=item.itemCode) }}"
              class="btn btn-sm btn-primary"
              >Edit</a
            >
            <form
              method="post"
              action="{{ url_for('product_blueprint.delete_product', itemCode=item.itemCode) }}"
            >
              <input
                type="submit"
                value="Delete"
                class="btn btn-sm btn-danger"
              />
            </form>
          </td> -->
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %} {% block scripts %}
<script>
  $(document).ready(function () {
    $("#data").DataTable({
      deferRender: true,
      processing: true,
      serverSide: true,
      ajax: {
        url: "/products/data",
        type: "GET",
        data: function (d) {
          d.search.value = $("#data_filter input").val();
        },
      },
      order: [[1, "asc"]],
      columns: [
        {
          orderable: false,
          data: null,
          render: function (data, type, row, meta) {
            return meta.row + meta.settings._iDisplayStart + 1;
          },
        },
        { orderable: true, data: "Kode Barang", name: "Kode Barang" },
        {
          orderable: true,
          data: "Nama Barang",
          name: "Nama Barang",
        },
        {
          orderable: false,
          data: null,
          render: function (data, type, row) {
            return (
              '<a href="/products/' +
              row["Kode Barang"] +
              "/edit" +
              '" class="btn btn-sm btn-outline-primary" title="Lihat Detail" aria-label="Lihat Detail"><span> <i class="ti ti-edit"></i> Edit </span></a>'
            );
          },
        },
      ],
      language: {
        url: "https://cdn.datatables.net/plug-ins/1.10.25/i18n/Indonesian.json",
      },
    });
  });

  // Fungsi untuk mengubah harga ke format mata uang Rupiah
  function formatToRupiah(price) {
    return new Intl.NumberFormat("id-ID", {
      style: "currency",
      currency: "IDR",
    }).format(Number(price));
  }

  // Mengambil semua elemen dengan id "price" dan mengonversi nilainya
  var priceElements = document.querySelectorAll("#price");
  priceElements.forEach(function (element) {
    var price = element.textContent;
    element.textContent = formatToRupiah(price);
  });

  function deleteProductConfirmation(item) {
    if (
      confirm(
        "Anda yakin ingin menghapus item " + item + " dari master produk?"
      )
    ) {
      return true;
    } else {
      return false;
    }
  }
</script>
{% endblock %}