routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_user, login_required, logout_user
from app import bcrypt
from src.controllers.dashboardController import dashboardIndex, dashboardSalesData
from src.controllers.productController import index, create, store, edit, update, delete
from src.controllers.transactionController import indexTrans, createTrans, storeTrans, detailTrans
from src.controllers.authController import registerPost, loginPost
from src.controllers.userController import getProfile, editProfile, updateProfile, updatePassword
from src.controllers.datasetController import importIndex, doImportFile
from src.controllers.miningController import eclatIndex, eclatMining, fpGrowthIndex, fpGrowthMining
from src.controllers.miningHistoryController import historyIndex, detailMiningProcess, deleteMiningProcess, generateReport

auth_blueprint = Blueprint('auth_blueprint', __name__, url_prefix='/')
dashboard_blueprint = Blueprint('dashboard_blueprint', __name__)
dataset_blueprint = Blueprint('dataset_blueprint', __name__)
product_blueprint = Blueprint('product_blueprint', __name__)
transaction_blueprint = Blueprint('transaction_blueprint', __name__)
mining_blueprint = Blueprint('mining_blueprint', __name__)
mining_history_blueprint = Blueprint('mining_history_blueprint', __name__)
user_blueprint = Blueprint('user_blueprint', __name__)


# ---------------------------------------------------------------------
# Authentication
@auth_blueprint.route("/", methods=["GET", "POST"])
def login():
    if request.method == 'GET': return render_template('auth/login.html')
    if request.method == 'POST': return loginPost(bcrypt)
    else: return "Method not allowed"


@auth_blueprint.route("/register", methods=["GET", "POST"])
def register():
    if request.method == 'GET': return render_template('auth/register.html')
    if request.method == 'POST': return registerPost(bcrypt)
    else: return "Method not allowed"

@auth_blueprint.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth_blueprint.login'))


# ---------------------------------------------------------------------
# Home
@dashboard_blueprint.route("/dashboard", methods=["GET"])
@login_required
def dashboard():
    return dashboardIndex()

@dashboard_blueprint.route("/transactions/sales-data", methods=["GET"])
@login_required
def sales_data():
    return dashboardSalesData()


# ---------------------------------------------------------------------
# Import Dataset
@dataset_blueprint.route("/import", methods=["GET", "POST"])
@login_required
def do_import():
    if request.method == 'GET': return importIndex()
    if request.method == 'POST': return doImportFile()
    else: return "Method not allowed"


# ---------------------------------------------------------------------
# Product
# @product_blueprint.route("/products", methods=["GET"])
# @login_required
# def list_product():
#     if request.method == 'GET': return index()
#     else: return "Method not allowed"

@product_blueprint.route("/products/")
@login_required
def list_product():
    return render_template('product/list_product.html')

@product_blueprint.route("/products/data", methods=["GET"])
@login_required
def list_product_data():
    return index()

@product_blueprint.route("/products/create", methods=["GET", "POST"])
@login_required
def create_product():
    if request.method == 'GET': return create()
    if request.method == 'POST': return store()
    else: return "Method not allowed"

@product_blueprint.route("/products/<itemCode>/edit", methods=["GET", "POST"])
@login_required
def edit_product(itemCode):
    if request.method == 'GET': return edit(itemCode)
    if request.method == 'POST': return update(itemCode)
    else: return "Method not allowed"

@product_blueprint.route("/products/<itemCode>/delete", methods=["POST"])
@login_required
def delete_product(itemCode):
    return delete(itemCode)


# ---------------------------------------------------------------------
# Transaction
@transaction_blueprint.route("/transaction/")
@login_required
def list_transaction():
    return render_template('transaction/list_transaction.html')

@transaction_blueprint.route("/transaction/data", methods=["GET"])
@login_required
def list_transaction_data():
    return indexTrans()

@transaction_blueprint.route("/transaction/create", methods=["GET", "POST"])
@login_required
def create_transaction():
    if request.method == 'GET': return createTrans()
    if request.method == 'POST': return storeTrans()
    else: return "Method not allowed"
    
@transaction_blueprint.route("/transaction/<transaction_id>/detail", methods=["GET"])
@login_required
def detail_transaction(transaction_id):
    return detailTrans(transaction_id)


# ---------------------------------------------------------------------
# Association Mining
@mining_blueprint.route("/eclat", methods=["GET", "POST"])
@login_required
def eclat_mining():
    if request.method == 'GET': return eclatIndex()
    if request.method == 'POST': return eclatMining()
    else: return "Method not allowed"
    
@mining_blueprint.route("/fp-growth", methods=["GET", "POST"])
@login_required
def fpgrowth_mining():
    if request.method == 'GET': return fpGrowthIndex()
    if request.method == 'POST': return fpGrowthMining()
    else: return "Method not allowed"


# ---------------------------------------------------------------------
# Mining History
@mining_history_blueprint.route("/mining-history", methods=["GET"])
@login_required
def mining_history():
    if request.method == 'GET': return historyIndex()
    else: return "Method not allowed"
    
@mining_history_blueprint.route("/mining-history/<process_id>/detail", methods=["GET"])
@login_required
def detail_mining_history(process_id):
    return detailMiningProcess(process_id)


@mining_history_blueprint.route("/mining-history/<process_id>/delete", methods=["POST"])
@login_required
def delete_mining_history(process_id):
    return deleteMiningProcess(process_id)

@mining_history_blueprint.route("/mining-history/<process_id>/report", methods=["GET"])
@login_required
def mining_history_report(process_id):
    return generateReport(process_id)


# ---------------------------------------------------------------------
# User
@user_blueprint.route("/profile", methods=["GET", "POST"])
@login_required
def profile():
    if request.method == 'GET': return getProfile()
    if request.method == 'POST': return updatePassword(bcrypt)
    else: return "Method not allowed"

@user_blueprint.route("/profile/<user_id>/edit", methods=["GET", "POST"])
@login_required
def edit_profile(user_id):
    if request.method == 'GET': return editProfile(user_id)
    if request.method == 'POST': return updateProfile(user_id)
    else: return "Method not allowed"

src/controllers/dashboardController.py
from flask import render_template, request, redirect, url_for, jsonify
from app import db
from src.models.product import Product
from src.models.transaction import Transaction
from src.models.user import User
from src.models.mining import MiningProcess
from flask_login import current_user
from sqlalchemy import func


def dashboardIndex():
    lenOfproducts = Product.query.count()
    lenOftransactions = Transaction.query.count()
    currentUser = User.query.filter_by(email=current_user.email).first()
    lenOfminingProcess = MiningProcess.query.count()
    
    return render_template('dashboard.html',
                           products=lenOfproducts,
                           transactions=lenOftransactions,
                           currentUser=currentUser,
                           miningProcess=lenOfminingProcess)
    
    
def dashboardSalesData():
    results = db.session.query(
        func.to_char(Transaction.date, 'YYYY-MM-01').label('month_start_date'),
        func.count(Transaction.transaction_id).label('total_transactions')
    ).group_by('month_start_date').order_by('month_start_date').all()

    data = [{'month_start_date': result[0], 'total_transactions': result[1]} for result in results]

    return jsonify({
            'data': data,
        })

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>SinarMart Analytics - {% block title %} {% endblock %}</title>
    <link
      rel="shortcut icon"
      type="image/png"
      href="/static/images/logos/sinarmart-logo-only.svg"
    />
    <!-- <link rel="stylesheet" href="../assets/css/styles.min.css" /> -->
    <link rel="stylesheet" href="/static/css/styles.min.css" />
  </head>

  <body>
    <div>{% block content %} {% endblock %}</div>

    <script src="/static/libs/jquery/dist/jquery.min.js"></script>
    <script src="/static/libs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="/static/js/sidebarmenu.js"></script>
    <script src="/static/js/app.min.js"></script>
    <script src="/static/libs/apexcharts/dist/apexcharts.min.js"></script>
    <script src="/static/libs/simplebar/dist/simplebar.js"></script>
    <script src="/static/js/dashboard.js"></script>
  </body>
</html>

templates/base_admin.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %} {% endblock %} | SinarMart Analytics</title>
    <link
      rel="shortcut icon"
      type="image/png"
      href="/static/images/logos/sinarmart-logo-only.svg"
    />
    <!-- <link rel="stylesheet" href="../assets/css/styles.min.css" /> -->
    <link rel="stylesheet" href="/static/css/styles.min.css" />

    <link
      rel="stylesheet"
      type="text/css"
      href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap5.css"
    />

    <link
      href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css"
      rel="stylesheet"
    />

    <style>
      .brand-logo {
        position: relative;
        z-index: 100;
      }
    </style>

    {% block styles %}{% endblock %}
  </head>

  <body>
    <!--  Body Wrapper -->
    <div
      class="page-wrapper"
      id="main-wrapper"
      data-layout="vertical"
      data-navbarbg="skin6"
      data-sidebartype="full"
      data-sidebar-position="fixed"
      data-header-position="fixed"
    >
      <!-- Sidebar Start -->
      <aside
        class="left-sidebar bg-primary text-white"
        style="
          background-image: url('/static/images/backgrounds/Sinarmart-Front-Edited.jpeg');
          background-size: cover;
          background-repeat: no-repeat;
          background-position: center;
          /* position: relative; */
        "
      >
        <div
          class="position-absolute top-0 start-0 w-100 h-100"
          style="
            background: linear-gradient(
              to bottom,
              rgba(0, 0, 0, 0.5) 0%,
              rgba(0, 0, 0, 0.7) 100%
            );
            opacity: 0.5; /* Atur nilai opacity di sini */
          "
        ></div>

        <!-- Sidebar scroll-->
        <div>
          <!-- <div
            class="brand-logo d-flex align-items-center justify-content-between"
          >
            <a href="./index.html" class="text-nowrap logo-img">
              <img
                src="/static/images/logos/sinarmart-logo.svg"
                width="180"
                alt=""
              />
            </a>
            <div
              class="close-btn d-xl-none d-block sidebartoggler cursor-pointer"
              id="sidebarCollapse"
            >
              <i class="ti ti-x fs-8"></i>
            </div>
          </div> -->

          <div
            class="brand-logo d-flex align-items-center justify-content-between"
            style="z-index: 100"
          >
            <a href="./index.html" class="text-nowrap logo-img">
              <img
                src="/static/images/logos/sinarmart-logo.svg"
                width="180"
                alt=""
              />
            </a>
            <div
              class="close-btn d-xl-none d-block sidebartoggler cursor-pointer"
              id="sidebarCollapse"
            >
              <i class="ti ti-x fs-8"></i>
            </div>
          </div>

          <!-- Sidebar navigation-->
          <nav class="sidebar-nav scroll-sidebar" data-simplebar="">
            <ul id="sidebarnav">
              <li class="nav-small-cap">
                <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
                <span class="hide-menu text-white">Home</span>
              </li>
              <li id="dashboard" class="sidebar-item">
                <a
                  class="sidebar-link text-white"
                  href="{{ url_for('dashboard_blueprint.dashboard') }}"
                  aria-expanded="false"
                >
                  <span>
                    <i class="ti ti-layout-dashboard"></i>
                  </span>
                  <span class="hide-menu">Dashboard</span>
                </a>
              </li>

              <li class="nav-small-cap">
                <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
                <span class="hide-menu text-white">PENAMBANGAN ASOSIASI</span>
              </li>

              <li id="import" class="sidebar-item">
                <a
                  class="sidebar-link text-white"
                  href="{{ url_for('dataset_blueprint.do_import') }}"
                  aria-expanded="false"
                >
                  <span>
                    <!-- <i class="ti ti-article"></i> -->
                    <i class="ti ti-table-import"></i>
                  </span>
                  <span class="hide-menu">Import Data Penjualan</span>
                </a>
              </li>

              <li id="product" class="sidebar-item">
                <a
                  class="sidebar-link text-white"
                  href="{{ url_for('product_blueprint.list_product') }}"
                  aria-expanded="false"
                >
                  <span>
                    <i class="ti ti-bottle"></i>
                  </span>
                  <span class="hide-menu">Data Barang</span>
                </a>
              </li>

              <li id="transaction" class="sidebar-item">
                <a
                  class="sidebar-link text-white"
                  href="{{ url_for('transaction_blueprint.list_transaction') }}"
                  aria-expanded="false"
                >
                  <span>
                    <i class="ti ti-shopping-cart"></i>
                  </span>
                  <span class="hide-menu">Data Transaksi</span>
                </a>
              </li>

              <li id="eclat" class="sidebar-item">
                <a
                  class="sidebar-link text-white"
                  href="{{ url_for('mining_blueprint.eclat_mining') }}"
                  aria-expanded="false"
                >
                  <span>
                    <i class="ti ti-diamond"></i>
                  </span>
                  <span class="hide-menu">Analisis ECLAT</span>
                </a>
              </li>

              <li id="fp-growth" class="sidebar-item">
                <a
                  class="sidebar-link text-white"
                  href="{{ url_for('mining_blueprint.fpgrowth_mining') }}"
                  aria-expanded="false"
                >
                  <span>
                    <i class="ti ti-diamond"></i>
                  </span>
                  <span class="hide-menu">Analisis FP-Growth</span>
                </a>
              </li>

              <li id="history" class="sidebar-item">
                <a
                  class="sidebar-link text-white"
                  href="{{ url_for('mining_history_blueprint.mining_history') }}"
                  aria-expanded="false"
                >
                  <span>
                    <i class="ti ti-history"></i>
                  </span>
                  <span class="hide-menu">Riwayat Analisis</span>
                </a>
              </li>

              <li class="nav-small-cap">
                <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
                <span class="hide-menu text-white">AUTENTIKASI</span>
              </li>

              <li id="account-setting" class="sidebar-item">
                <a
                  class="sidebar-link text-white"
                  href="{{ url_for('user_blueprint.profile') }}"
                  aria-expanded="false"
                >
                  <span>
                    <i class="ti ti-user-circle"></i>
                  </span>
                  <span class="hide-menu">Pengaturan Akun</span>
                </a>
              </li>

              <li id="logout" class="sidebar-item">
                <a
                  class="sidebar-link text-white"
                  href="{{ url_for('auth_blueprint.logout') }}"
                  aria-expanded="false"
                  onclick="return logoutConfirmation()"
                >
                  <span>
                    <i class="ti ti-logout"></i>
                  </span>
                  <span class="hide-menu">Logout</span>
                </a>
              </li>
            </ul>
          </nav>
          <!-- End Sidebar navigation -->
        </div>
        <!-- End Sidebar scroll-->
      </aside>
      <!--  Sidebar End -->
      <!--  Main wrapper -->
      <div class="body-wrapper">
        <!--  Header Start -->
        <!-- <header class="app-header">
          <nav class="navbar navbar-expand-lg navbar-light">
            <ul class="navbar-nav">
              <li class="nav-item d-block d-xl-none">
                <a
                  class="nav-link sidebartoggler nav-icon-hover"
                  id="headerCollapse"
                  href="javascript:void(0)"
                >
                  <i class="ti ti-menu-2"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link nav-icon-hover" href="javascript:void(0)">
                  <i class="ti ti-bell-ringing"></i>
                  <div class="notification bg-primary rounded-circle"></div>
                </a>
              </li>
            </ul>
            <div
              class="navbar-collapse justify-content-end px-0"
              id="navbarNav"
            >
              <ul
                class="navbar-nav flex-row ms-auto align-items-center justify-content-end"
              >
                <li class="nav-item dropdown">
                  <a
                    class="nav-link nav-icon-hover"
                    href="javascript:void(0)"
                    id="drop2"
                    data-bs-toggle="dropdown"
                    aria-expanded="false"
                  >
                    <img
                      src="/static/images/profile/user-1.jpg"
                      alt=""
                      width="35"
                      height="35"
                      class="rounded-circle"
                    />
                  </a>
                  <div
                    class="dropdown-menu dropdown-menu-end dropdown-menu-animate-up"
                    aria-labelledby="drop2"
                  >
                    <div class="message-body">
                      <a
                        href="javascript:void(0)"
                        class="d-flex align-items-center gap-2 dropdown-item"
                      >
                        <i class="ti ti-user fs-6"></i>
                        <p class="mb-0 fs-3">Pengaturan Akun</p>
                      </a>
                      <a
                        href="{{ url_for('auth_blueprint.logout') }}"
                        class="btn btn-outline-primary mx-3 mt-2 d-block"
                        >Logout</a
                      >
                    </div>
                  </div>
                </li>
              </ul>
            </div>
          </nav>
        </header> -->
        <!--  Header End -->

        <div class="container">
          <div class="p-5">{% block content %} {% endblock %}</div>
        </div>
      </div>
    </div>

    <script>
      function setActiveNavLink(linkId) {
        var allNavLinks = document.querySelectorAll(".sidebar-item");
        allNavLinks.forEach(function (navLink) {
          navLink.classList.remove("active");
        });

        var selectedNavLink = document.getElementById(linkId);
        selectedNavLink.classList.add("active");

        var currentNavLink = selectedNavLink.querySelector(".sidebar-link");
        currentNavLink.style.backgroundColor = "#fff"; // Replace 'your-color' with the desired color
        currentNavLink.classList.remove("text-white");
        currentNavLink.classList.add("text-primary");
      }

      // Get the current page identifier from the Flask template
      var currentPage = "{{ current_page }}"; // Replace 'current_page' with the actual variable containing the page identifier

      // Call setActiveNavLink based on the current page
      setActiveNavLink(currentPage);
    </script>

    <script src="/static/libs/jquery/dist/jquery.min.js"></script>
    <script src="/static/libs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="/static/js/sidebarmenu.js"></script>
    <script src="/static/js/app.min.js"></script>
    <script src="/static/libs/apexcharts/dist/apexcharts.min.js"></script>
    <script src="/static/libs/simplebar/dist/simplebar.js"></script>
    <script src="/static/js/dashboard.js"></script>

    <script
      type="text/javascript"
      charset="utf8"
      src="https://code.jquery.com/jquery-3.6.0.min.js"
    ></script>
    <script
      type="text/javascript"
      charset="utf8"
      src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js"
    ></script>
    <script
      type="text/javascript"
      charset="utf8"
      src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap5.js"
    ></script>

    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    {% block scripts %}{% endblock %}

    <script>
      function logoutConfirmation() {
        if (confirm("Anda yakin ingin keluar?")) {
          return true;
        } else {
          return false;
        }
      }
    </script>
  </body>
</html>

templates/dashboard.html
{% extends 'base_admin.html' %} {% block title %} Dashboard {% endblock %} {%
set current_page = 'dashboard' %} {% block content %}
<div class="container-fluid">
  <div class="row">
    <h3 class="mb-5">Hi! <b>{{currentUser.name}}</b></h3>

    <div class="col-lg-4">
      <div class="card">
        <div class="card-body">
          <div class="row alig n-items-start">
            <div class="col-8">
              <h5 class="card-title mb-9 fw-semibold">Master Produk</h5>
              <h4 class="fw-semibold mb-3">{{products}}</h4>
              <div class="d-flex align-items-center pb-1">
                <!-- <span
                  class="me-2 rounded-circle bg-light-danger round-20 d-flex align-items-center justify-content-center"
                >
                  <i class="ti ti-arrow-down-right text-danger"></i>
                </span> -->
                <p class="text-dark me-1 fs-3 mb-0">Total Produk</p>
                <p class="fs-3 mb-0"></p>
              </div>
            </div>
            <div class="col-4">
              <div class="d-flex justify-content-end">
                <div
                  class="text-white bg-secondary rounded-circle p-6 d-flex align-items-center justify-content-center"
                >
                  <i class="ti ti-apple fs-6"></i>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-4">
      <div class="card">
        <div class="card-body">
          <div class="row alig n-items-start">
            <div class="col-8">
              <h5 class="card-title mb-9 fw-semibold">Transaksi</h5>
              <h4 class="fw-semibold mb-3">{{transactions}}</h4>
              <div class="d-flex align-items-center pb-1">
                <!-- <span
                  class="me-2 rounded-circle bg-light-danger round-20 d-flex align-items-center justify-content-center"
                >
                  <i class="ti ti-arrow-down-right text-danger"></i>
                </span> -->
                <p class="text-dark me-1 fs-3 mb-0">Total Transaksi</p>
                <p class="fs-3 mb-0"></p>
              </div>
            </div>
            <div class="col-4">
              <div class="d-flex justify-content-end">
                <div
                  class="text-white bg-secondary rounded-circle p-6 d-flex align-items-center justify-content-center"
                >
                  <i class="ti ti-shopping-cart fs-6"></i>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-4">
      <div class="card">
        <div class="card-body">
          <div class="row alig n-items-start">
            <div class="col-8">
              <h5 class="card-title mb-9 fw-semibold">Riwayat</h5>
              <h4 class="fw-semibold mb-3">{{miningProcess}}</h4>
              <div class="d-flex align-items-center pb-1">
                <!-- <span
                  class="me-2 rounded-circle bg-light-danger round-20 d-flex align-items-center justify-content-center"
                >
                  <i class="ti ti-arrow-down-right text-danger"></i>
                </span> -->
                <p class="text-dark me-1 fs-3 mb-0">Total Penambangan</p>
                <p class="fs-3 mb-0"></p>
              </div>
            </div>
            <div class="col-4">
              <div class="d-flex justify-content-end">
                <div
                  class="text-white bg-secondary rounded-circle p-6 d-flex align-items-center justify-content-center"
                >
                  <i class="ti ti-diamond fs-6"></i>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="card-body">
      <div
        class="d-sm-flex d-block align-items-center justify-content-between mb-9"
      >
        <div class="mb-3 mb-sm-0">
          <h5 class="card-title fw-semibold">Ikhtisar Penjualan</h5>
        </div>
        <!-- <div>
          <select class="form-select">
            <option value="1">March 2023</option>
            <option value="2">April 2023</option>
            <option value="3">May 2023</option>
            <option value="4">June 2023</option>
          </select>
        </div> -->
      </div>
      <div id="chart"></div>
    </div>

    <!-- <h5 class="mt-5">Ketentuan Penggunaan:</h5>
    <ul>
      <li>- Data Laporan penjualan disiapkan terlebih dahulu</li>
      <li>- Data penjualan harus memiliki nomor faktur dan kode barang</li>
      <li>- Import data kedalam sistem sesuai ketentuan</li>
      <li>
        - Ketika data penjualan diimport, otomatis sistem akan menyimpan data
        transaksi dan produk
      </li>
      <li>
        - Lakukan analisis asosiasi dengan pilihan algoritma yaitu ECLAT atau
        FP-Growth
      </li>
      <li>- Download PDF hasil analisis jika perlu.</li>
    </ul> -->
  </div>
</div>

{% endblock %}