routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_user, login_required, logout_user
from app import bcrypt
from src.controllers.dashboardController import dashboardIndex, dashboardSalesData
from src.controllers.productController import index, create, store, edit, update, delete
from src.controllers.transactionController import indexTrans, createTrans, storeTrans, detailTrans
from src.controllers.authController import registerPost, loginPost
from src.controllers.userController import getProfile, editProfile, updateProfile, updatePassword
from src.controllers.datasetController import importIndex, doImportFile
from src.controllers.miningController import eclatIndex, eclatMining, fpGrowthIndex, fpGrowthMining
from src.controllers.miningHistoryController import historyIndex, detailMiningProcess, deleteMiningProcess, generateReport

auth_blueprint = Blueprint('auth_blueprint', __name__, url_prefix='/')
dashboard_blueprint = Blueprint('dashboard_blueprint', __name__)
dataset_blueprint = Blueprint('dataset_blueprint', __name__)
product_blueprint = Blueprint('product_blueprint', __name__)
transaction_blueprint = Blueprint('transaction_blueprint', __name__)
mining_blueprint = Blueprint('mining_blueprint', __name__)
mining_history_blueprint = Blueprint('mining_history_blueprint', __name__)
user_blueprint = Blueprint('user_blueprint', __name__)


# ---------------------------------------------------------------------
# Authentication
@auth_blueprint.route("/", methods=["GET", "POST"])
def login():
    if request.method == 'GET': return render_template('auth/login.html')
    if request.method == 'POST': return loginPost(bcrypt)
    else: return "Method not allowed"


@auth_blueprint.route("/register", methods=["GET", "POST"])
def register():
    if request.method == 'GET': return render_template('auth/register.html')
    if request.method == 'POST': return registerPost(bcrypt)
    else: return "Method not allowed"

@auth_blueprint.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth_blueprint.login'))


# ---------------------------------------------------------------------
# Home
@dashboard_blueprint.route("/dashboard", methods=["GET"])
@login_required
def dashboard():
    return dashboardIndex()

@dashboard_blueprint.route("/transactions/sales-data", methods=["GET"])
@login_required
def sales_data():
    return dashboardSalesData()


# ---------------------------------------------------------------------
# Import Dataset
@dataset_blueprint.route("/import", methods=["GET", "POST"])
@login_required
def do_import():
    if request.method == 'GET': return importIndex()
    if request.method == 'POST': return doImportFile()
    else: return "Method not allowed"


# ---------------------------------------------------------------------
# Product
# @product_blueprint.route("/products", methods=["GET"])
# @login_required
# def list_product():
#     if request.method == 'GET': return index()
#     else: return "Method not allowed"

@product_blueprint.route("/products/")
@login_required
def list_product():
    return render_template('product/list_product.html')

@product_blueprint.route("/products/data", methods=["GET"])
@login_required
def list_product_data():
    return index()

@product_blueprint.route("/products/create", methods=["GET", "POST"])
@login_required
def create_product():
    if request.method == 'GET': return create()
    if request.method == 'POST': return store()
    else: return "Method not allowed"

@product_blueprint.route("/products/<itemCode>/edit", methods=["GET", "POST"])
@login_required
def edit_product(itemCode):
    if request.method == 'GET': return edit(itemCode)
    if request.method == 'POST': return update(itemCode)
    else: return "Method not allowed"

@product_blueprint.route("/products/<itemCode>/delete", methods=["POST"])
@login_required
def delete_product(itemCode):
    return delete(itemCode)


# ---------------------------------------------------------------------
# Transaction
@transaction_blueprint.route("/transaction/")
@login_required
def list_transaction():
    return render_template('transaction/list_transaction.html')

@transaction_blueprint.route("/transaction/data", methods=["GET"])
@login_required
def list_transaction_data():
    return indexTrans()

@transaction_blueprint.route("/transaction/create", methods=["GET", "POST"])
@login_required
def create_transaction():
    if request.method == 'GET': return createTrans()
    if request.method == 'POST': return storeTrans()
    else: return "Method not allowed"
    
@transaction_blueprint.route("/transaction/<transaction_id>/detail", methods=["GET"])
@login_required
def detail_transaction(transaction_id):
    return detailTrans(transaction_id)


# ---------------------------------------------------------------------
# Association Mining
@mining_blueprint.route("/eclat", methods=["GET", "POST"])
@login_required
def eclat_mining():
    if request.method == 'GET': return eclatIndex()
    if request.method == 'POST': return eclatMining()
    else: return "Method not allowed"
    
@mining_blueprint.route("/fp-growth", methods=["GET", "POST"])
@login_required
def fpgrowth_mining():
    if request.method == 'GET': return fpGrowthIndex()
    if request.method == 'POST': return fpGrowthMining()
    else: return "Method not allowed"


# ---------------------------------------------------------------------
# Mining History
@mining_history_blueprint.route("/mining-history", methods=["GET"])
@login_required
def mining_history():
    if request.method == 'GET': return historyIndex()
    else: return "Method not allowed"
    
@mining_history_blueprint.route("/mining-history/<process_id>/detail", methods=["GET"])
@login_required
def detail_mining_history(process_id):
    return detailMiningProcess(process_id)


@mining_history_blueprint.route("/mining-history/<process_id>/delete", methods=["POST"])
@login_required
def delete_mining_history(process_id):
    return deleteMiningProcess(process_id)

@mining_history_blueprint.route("/mining-history/<process_id>/report", methods=["GET"])
@login_required
def mining_history_report(process_id):
    return generateReport(process_id)


# ---------------------------------------------------------------------
# User
@user_blueprint.route("/profile", methods=["GET", "POST"])
@login_required
def profile():
    if request.method == 'GET': return getProfile()
    if request.method == 'POST': return updatePassword(bcrypt)
    else: return "Method not allowed"

@user_blueprint.route("/profile/<user_id>/edit", methods=["GET", "POST"])
@login_required
def edit_profile(user_id):
    if request.method == 'GET': return editProfile(user_id)
    if request.method == 'POST': return updateProfile(user_id)
    else: return "Method not allowed"

src/controllers/transactionController.py
from flask import render_template, request, redirect, url_for, flash, jsonify
from app import db
from src import utils
import uuid
from src.models.transaction import Transaction, TransactionProduct
from src.models.product import Product
from sqlalchemy import func, text, or_
from datetime import datetime


def indexTrans():
    try:
        # Mengambil parameter paging dan sorting dari permintaan Ajax
        draw = int(request.args.get('draw', 1))
        start = int(request.args.get('start', 0))
        length = int(request.args.get('length', 10))
        order_column_index = int(request.args.get('order[0][column]', 1))
        order_dir = request.args.get('order[0][dir]', 'asc')
        search_value = request.args.get('search[value]', '')

        # Menentukan kolom apa yang dapat diurutkan
        sortable_columns = ['transaction_id', 'date']
        order_column_name = sortable_columns[min(order_column_index, len(sortable_columns) - 1)]

        # Menentukan arah pengurutan
        if order_dir == 'asc':
            order_clause = f"{order_column_name} ASC"
        else:
            order_clause = f"{order_column_name} DESC"

        # Mengambil data untuk halaman tertentu dengan paging dan sorting        
        query = Transaction.query.filter(
            or_(
                func.cast(Transaction.transaction_id, db.String).ilike(f"%{search_value}%"),
                func.cast(Transaction.date, db.String).ilike(f"%{search_value}%"),
            )
        )
        
        total_records = query.count()
        transactionsData = query.order_by(text(order_clause)).offset(start).limit(length).all()

        transactions = []
        for transaction in transactionsData:
            transactions.append({
                'Faktur': transaction.transaction_id,
                'Tanggal Transaksi': transaction.date.strftime('%Y-%m-%d'),
            })

        return jsonify({
            'draw': draw,
            'recordsTotal': total_records,
            'recordsFiltered': total_records,
            'data': transactions,
        })
    except Exception as e:
        print(f"Error in indexTrans: {str(e)}")
        return jsonify({'error': 'Internal Server Error'}), 500

def clean_value(value):
    return value.replace('`', '')


def createTrans():
    products = Product.query.all()
    
    cleaned_products = [{'itemCode': product.itemCode, 'name': clean_value(product.name)} for product in products]
    
    return render_template('transaction/create_transaction.html', products=cleaned_products)


def storeTrans(): 
    new_uuid = uuid.uuid4()
    transaction_id = str(new_uuid)  
    # transaction_id = request.form.get('transaction_id')  
    date = request.form.get('date')
    
    new_transaction = Transaction(
        transaction_id = transaction_id,
        date = date,
        total_price=0,
    )
    
    db.session.add(new_transaction)
    
    item_codes = request.form.getlist('itemCode[]')
    quantities = request.form.getlist('quantity[]')
    item_prices = []
    
    for code in item_codes:
        if code == "Select...":
            continue
        
        item = Product.query.filter_by(itemCode=code).first()
        item_prices.append(item.price)
    
    total_price = 0
    for item_code, price, quantity in zip(item_codes, item_prices, quantities):
        if item_code == "Select...":
            continue
        
        new_transaction_product = TransactionProduct(itemCode=item_code, quantity=quantity)
        new_transaction.products.append(new_transaction_product)
        
        total_price += price * int(quantity)

    new_transaction.total_price = total_price
    db.session.commit()
    
    flash('Transaksi baru berhasil ditambahkan.')
    
    return redirect(url_for('transaction_blueprint.list_transaction'))


def detailTrans(transaction_id):
    transaction = Transaction.query.get(transaction_id)
    
    transaction_products = db.session.query(TransactionProduct, Product.name, Product.price).\
        filter(TransactionProduct.itemCode == Product.itemCode).\
        filter(TransactionProduct.transaction_id == transaction_id).all()
    
    return render_template('transaction/detail_transaction.html', transaction=transaction, transaction_products=transaction_products)

templates/transaction/create_transaction.html
{% extends 'base_admin.html' %} {% block title %} Tambah Transaksi {% endblock
%} {% block content %}
<h3 class="mb-5">Tambah Transaksi</h3>

<div class="card">
  <div class="card-body">
    <form
      action="{{ url_for('transaction_blueprint.create_transaction') }}"
      method="POST"
      onsubmit="logSelectedProducts()"
    >
      <div class="mb-3">
        <input
          type="text"
          class="form-control"
          id="transaction_id"
          name="transaction_id"
          hidden
        />
      </div>

      <div class="mb-3">
        <label for="date" class="form-label">Tanggal Transaksi</label>
        <input
          type="date"
          class="form-control"
          id="date"
          name="date"
          required
        />
      </div>

      <div class="card mb-0">
        <div class="card-body p-4">
          <div id="product-fields" class="mb-3">
            <!-- Initial product field -->
            <div class="product-field">
              <div class="d-flex justify-content-start">
                <div class="d-flex flex-column p-3">
                  <label for="disabledSelect" class="form-label"
                    >Pilih Produk</label
                  >
                  <select
                    class="form-select product-select"
                    name="itemCode[]"
                    required
                  >
                    <option></option>
                    {% for item in products %}
                    <option value="{{ item.itemCode }}">{{ item.name }}</option>
                    {% endfor %}
                  </select>
                </div>
                <div class="d-flex flex-column p-3">
                  <label for="quantity" class="form-label">Kuantitas</label>
                  <input
                    type="number"
                    class="form-control"
                    name="quantity[]"
                    min="1"
                    required
                  />
                </div>
                <div class="d-flex flex-column p-3">
                  <button
                    type="button"
                    class="btn btn-outline-danger remove-product mt-auto"
                  >
                    <span> <i class="ti ti-trash"></i> Hapus </span>
                  </button>
                </div>
              </div>
            </div>
          </div>

          <button
            type="button"
            class="btn btn-outline-primary mt-3 ms-3"
            id="add-product"
          >
            Tambah Produk
          </button>
        </div>
      </div>
      <button
        type="submit"
        class="btn btn-primary mt-3 d-none"
        id="submit-transaction"
      >
        Simpan Transaksi
      </button>
      <a
        href="{{ url_for('transaction_blueprint.list_transaction') }}"
        class="btn btn-light mt-3"
      >
        Batal
      </a>
    </form>
  </div>
</div>
{% endblock %} {% block scripts %}

<script>
  // Fungsi untuk menambahkan produk
  $("#add-product").click(function () {
    var productField = createProductField();
    productField.appendTo("#product-fields");

    // Setel lebar elemen select setiap kali elemen baru ditambahkan
    productField.find(".product-select").select2({
      width: "300px",
      placeholder: "Select...",
    });

    checkSubmitButtonVisibility();
  });

  // Fungsi untuk membuat elemen produk baru
  function createProductField() {
    var productField = $("<div class='product-field'></div>");

    productField.html(`
      <div class="d-flex justify-content-start">
        <div class="d-flex flex-column p-3">
          <label for="disabledSelect" class="form-label">Pilih Produk</label>
          <select class="form-select product-select" name="itemCode[]" required>
            <option></option>
            {% for item in products %}
            <option value="{{ item.itemCode }}">{{ item.name }}</option>
            {% endfor %}
          </select>
        </div>
        <div class="d-flex flex-column p-3">
          <label for="quantity" class="form-label">Kuantitas</label>
          <input type="number" class="form-control" name="quantity[]" min="1" required  />
        </div>
        <div class="d-flex flex-column p-3">
          <button type="button" class="btn btn-outline-danger remove-product mt-auto">
            <span> <i class="ti ti-trash"></i> Hapus </span>
          </button>
        </div>
      </div>
    `);

    return productField;
  }

  // Fungsi untuk menghapus produk
  $("#product-fields").on("click", ".remove-product", function () {
    if ($("#product-fields .product-field").length > 1) {
      $(this).closest(".product-field").remove();
      checkSubmitButtonVisibility();
    }
  });

  function checkSubmitButtonVisibility() {
    if ($("#product-fields .product-field").length > 0) {
      $("#submit-transaction").removeClass("d-none");
    } else {
      $("#submit-transaction").addClass("d-none");
    }
  }

  function logSelectedProducts() {
    var selectedProducts = [];

    $(".product-field").each(function () {
      var productSelect = $(this).find(".product-select");
      var productQuantity = $(this).find("input[name='quantity[]']").val();

      if (productSelect.val() && productQuantity !== "") {
        var productName = productSelect.find(":selected").text();
        selectedProducts.push({
          name: productName,
          quantity: productQuantity,
        });
      }
    });

    console.log("Daftar Produk yang Diproses:");
    console.log(selectedProducts);
  }

  // Menginisialisasi Select2 pada elemen yang sudah ada
  $(".product-select").select2({
    width: "300px",
    placeholder: "Select...",
  });
</script>

{% endblock %}

templates/transaction/detail_transaction.html
{% extends 'base_admin.html' %} {% block title %} Detail Transaksi {% endblock
%} {% block content %}

<h3 class="mb-5">Detail Transaksi</h3>

<div class="card">
  <div class="card-body">
    <h5>Detail Transaksi</h5>

    <table class="table table-borderless">
      <tbody>
        <tr>
          <th scope="row" width="15%" style="padding: 5px 0px !important">
            No. Faktur
          </th>
          <td style="padding: 5px 0px !important">
            {{ transaction.transaction_id }}
          </td>
        </tr>
        <tr>
          <th scope="row" style="padding: 5px 0px !important">Tanggal</th>
          <td id="transactionDate" style="padding: 5px 0px !important">
            {{ transaction.date }}
          </td>
        </tr>
        <!-- <tr>
          <th scope="row" style="padding: 5px 0px !important">Total Bayar</th>
          <td id="totalPrice" style="padding: 5px 0px !important">
            {{ transaction.total_price }}
          </td>
        </tr> -->
      </tbody>
    </table>

    <a
      href="{{ url_for('transaction_blueprint.list_transaction') }}"
      class="btn btn-light mt-3"
    >
      Kembali
    </a>
  </div>
</div>

<div class="card">
  <div class="card-body">
    <h5 class="my-3">Daftar Produk Dalam Transaksi</h5>

    <table class="table" id="transactionProductsData">
      <thead>
        <tr>
          <th scope="col">No</th>
          <th scope="col">Kode Barang</th>
          <th scope="col">Nama Barang</th>
          <!-- <th scope="col">Harga Jual</th>
          <th scope="col">Kuantitas</th>
          <th scope="col">Sub Total</th> -->
        </tr>
      </thead>
      <tbody>
        {% for item, itemName, itemPrice in transaction_products %}
        <tr>
          <td>{{ loop.index }}</td>
          <td>{{ item.itemCode }}</td>
          <td>{{ itemName }}</td>
          <!-- <td id="itemPrice">{{ itemPrice }}</td>
          <td>{{ item.quantity }}</td>
          <td id="subTotalPrice">{{ itemPrice * item.quantity }}</td> -->
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %} {% block scripts %}
<script>
  // datatable
  $(document).ready(function () {
    $("#transactionProductsData").DataTable({
      language: {
        url: "https://cdn.datatables.net/plug-ins/1.10.25/i18n/Indonesian.json",
      },
    });
  });

  // Konversi integer ke nilai rupiah
  function formatToRupiah(price) {
    return new Intl.NumberFormat("id-ID", {
      style: "currency",
      currency: "IDR",
    }).format(Number(price));
  }

  var priceElement = document.querySelector("#totalPrice");
  var totalPrice = priceElement.textContent;
  priceElement.textContent = formatToRupiah(totalPrice);

  var priceElements = document.querySelectorAll("#itemPrice, #subTotalPrice");

  priceElements.forEach(function (element) {
    var price = element.textContent;
    element.textContent = formatToRupiah(price);
  });

  // Ubah format tanggal transaksi
  var transactionDateElement = document.querySelector("#transactionDate");
  var dateString = transactionDateElement.textContent;

  var dateParts = dateString.split("-");
  var year = dateParts[0];
  var month = dateParts[1];
  var day = dateParts[2];

  var formattedDate = day + "-" + month + "-" + year;

  transactionDateElement.textContent = formattedDate;
</script>
{% endblock %}

templates/transaction/list_transaction.html
{% extends 'base_admin.html' %} {% block title %} Daftar Transaksi {% endblock
%} {% set current_page = 'transaction' %} {% block content %}

<div class="d-flex justify-content-between mb-5">
  <h3>Data Transaksi</h3>
  <div>
    <a
      href="{{ url_for('transaction_blueprint.create_transaction') }}"
      class="btn btn-primary"
      >Tambah Transaksi</a
    >
  </div>
</div>

<div class="card">
  <div class="card-body">
    {% with messages = get_flashed_messages() %} {% if messages %}
    <div class="alert alert-success" role="alert">{{ messages[0] }}</div>
    {% endif %} {% endwith %}

    <table id="transactionData" class="table">
      <thead>
        <tr>
          <th scope="col">No</th>
          <th scope="col">No. Faktur</th>
          <th scope="col">Tanggal Transaksi</th>
          <!-- <th scope="col">Total Bayar</th> -->
          <th scope="col">Tindakan</th>
        </tr>
      </thead>
      <tbody>
        {% for transaction in transactions %}
        <tr>
          <td>{{ loop.index }}</td>
          <td>{{ transaction.Faktur }}</td>
          <td id="transactionDate">{{ transaction['Tanggal Transaksi'] }}</td>
          <td>
            <div class="d-flex justify-content-left">
              <a
                href="{{ url_for('transaction_blueprint.detail_transaction', transaction_id=transaction.Faktur) }}"
                class="btn btn-sm btn-outline-primary"
                title="Lihat Detail"
                aria-label="Lihat Detail"
                ><span> <i class="ti ti-eye"></i> Detail </span></a
              >
            </div>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %} {% block scripts %}
<script>
  $(document).ready(function () {
    $("#transactionData").DataTable({
      deferRender: true,
      processing: true,
      serverSide: true,
      ajax: {
        url: "/transaction/data",
        type: "GET",
        data: function (d) {
          d.search.value = $("#transactionData_filter input").val();
        },
      },
      order: [[1, "asc"]],
      columns: [
        {
          orderable: false,
          data: null,
          render: function (data, type, row, meta) {
            return meta.row + meta.settings._iDisplayStart + 1;
          },
        },
        { orderable: true, data: "Faktur", name: "Faktur" },
        {
          orderable: true,
          data: "Tanggal Transaksi",
          name: "Tanggal Transaksi",
        },
        {
          orderable: false,
          data: null,
          render: function (data, type, row) {
            return (
              '<a href="/transaction/' +
              row["Faktur"] +
              "/detail" +
              '" class="btn btn-sm btn-outline-primary" title="Lihat Detail" aria-label="Lihat Detail"><span> <i class="ti ti-eye"></i> Detail </span></a>'
            );
          },
        },
      ],
      language: {
        url: "https://cdn.datatables.net/plug-ins/1.10.25/i18n/Indonesian.json",
      },
    });
  });

  function formatToRupiah(price) {
    return new Intl.NumberFormat("id-ID", {
      style: "currency",
      currency: "IDR",
    }).format(Number(price));
  }

  // Mengambil semua elemen dengan id "price" dan mengonversi nilainya
  var priceElements = document.querySelectorAll("#price");
  priceElements.forEach(function (element) {
    var price = element.textContent;
    element.textContent = formatToRupiah(price);
  });

  // Ubah format tanggal transaksi
  // var transactionDateElements = document.querySelectorAll("#transactionDate");

  // transactionDateElements.forEach(function (element) {
  //   var dateString = element.textContent;

  //   var dateParts = dateString.split("-");
  //   var year = dateParts[0];
  //   var month = dateParts[1];
  //   var day = dateParts[2];

  //   var formattedDate = day + "-" + month + "-" + year;

  //   element.textContent = formattedDate;
  // });
</script>
{% endblock %}